modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mixins]]
config="atlas-core-common.mixins.json"

[[mods]]
modId = "atlas-core"
version = "${version}"
displayName = "Atlas Core"
authors = "Alexandra"
description = '''
A mod library made for Atlas mods
'''
#logoFile = ""

[[dependencies.atlas-core]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.atlas-core]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.atlas-core]]
modId = "cloth-config"
mandatory = true
versionRange = "[15.0.127,)"
ordering = "AFTER"
side = "BOTH"