modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mixins]]
config="atlas-lib-common.mixins.json"

[[mods]]
modId = "atlas-lib"
version = "${version}"
displayName = "Atlas Lib"
authors = "Alexandra"
description = '''
A mod library made for Atlas mods
'''
#logoFile = ""

[[dependencies.atlas-lib]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.atlas-lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.atlas-lib]]
modId = "cloth-config"
mandatory = true
versionRange = "[15.0.127,)"
ordering = "AFTER"
side = "BOTH"